name: Collect Queue Times
on:
  schedule:
    - cron: "*/15 * * * *"  # every 15 minutes (UTC)
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: queue-times-collector
  cancel-in-progress: false

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Ping collector (Vercel)
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          set -euo pipefail
          echo "Starting collection at $(date -Is)"
          # Call your Vercel cron endpoint (requires Authorization header)
          curl -fsS -H "Authorization: Bearer ${CRON_SECRET}" \
            "${VERCEL_URL%/}/api/cron/collect-queue-times" | tee /dev/stderr

      - name: Quick health ping (optional)
        if: always()
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          curl -fsS "${VERCEL_URL%/}/api/cron/collect-queue-times?quick=true" || true
